### ISSUE TITLE
3.0.2 is missing from Maven

### ISSUE THREAD

**Issue by p-himik** [luaj/luaj#62] opened 2019-12-08 09:09 UTC
It seems that only 3.0.1 has been uploaded.

**Comment by Enyby** [comment] 2019-12-08 22:15
Duplicate of https://github.com/luaj/luaj/issues/58

**Closed by Enyby** 2019-12-08 22:15 UTC

**Comment by p-himik** [comment] 2019-12-08 22:18
@Enyby Given that the authors cannot be reached but the project is still alive, would it make sense to change the artifact to something that's available? So that new versions could be uploaded to Maven.

**Comment by Enyby** [comment] 2019-12-08 22:21
The project is not alive. The project is dead. And this is a fork.

**Comment by p-himik** [comment] 2019-12-08 22:23
I mean this particular fork, yes. Whether to consider it a standalone project or not is just semantics.

But the fork is very much alive. At least, it seems that way.
Why not give it its own Maven coordinates?

**Comment by Enyby** [comment] 2019-12-08 22:29
I did not work with Maven, so I won’t tell you anything. If you know how to fix this whole thing, you can make a Pull Request.
